exclude_paths:
  - "venv"
  - "virtualenv"
  - "**/migrations/*"
  - "*.pyc"

engines:
  sonar-python:
    enabled: true
    config:
      test_patterns:
        "**test_*.py"
  pep8:
    enabled: true